config/routes.rb
TeamProject::Application.routes.draw do

  root to: "pages#home"

  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions",
    :registrations => "users/registrations"
  }

  resources :teams, only: [:show, :update, :edit] do
    resource :campaign, only: [:update]
    resources :users, only: [:show, :destroy] do
      resources :activities, only: [:create, :destroy]
    end
  end

  resources :activities, :only => :show do
    member do
      get :upvote
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    Rails.env.development? || (username == 'admin' && password == ENV['SIDEKIQ_PASSWORD'])
  end
end

app/views/partials/_employees.html.slim
.ft-content.row-fluid role="main"
  .span8
    section
      h1.lead Zarządzanie pracownikami

      table.table.table-striped
        thead
          tr
            th Imię i nazwisko
            th Zebrana kwota
            th Data rejestracji
            th
        tbody
          - for user in team.users
            tr
              td= "#{user.first_name} #{user.last_name}"
              td #{user.total_fundraiser} zł
              td= l user.created_at
              td
                - if user != current_user
                  = link_to 'Usuń', team_user_path(team, user), :method => :destroy, :confirm => true, :class => 'btn btn-danger'


  .ft-sidebar.span4
    section
      h1.lead Dodaj nowego pracownika
      p Wystarczy, że wyślesz swoim pracownikom następujący link rejestracyjny:
      pre style='font-size: 80%'
        = new_user_registration_url(:t => team.token).html_safe

app/views/partials/_feed.slim
.ft-feed
  - for activity in feed
    article.ft-feed-item.media class=(activity.user == current_user ? 'ft-feed-item--mine' : '')
      .pull-right
        .ft-feed-item-value
          ' Wartość wpisu:
          b
            span data-value-updatable=""= activity.value
            '  zł
        - if activity.user != current_user && activity.upvotes.where(:user_id => current_user).count == 0
          = link_to 'Podbij o 1 zł', upvote_activity_path(activity.id),
            :data => { value: 1, :remote => true },
            :class => "ft-feed-item-button btn btn-success btn-small"
      .media-object
        = image_tag activity.user.picture("large"), width: 64, height: 64
      .media-body
        h4.media-heading= activity.user.full_name
        p= activity.description
        .muted= activity.created_at

app/views/partials/_goal.html.slim
- if team.fundraiser.present?
  header
    h1.lead Aktualny cel
    = link_to  team.fundraiser.url do
      = image_tag(team.fundraiser.picture, :style => "margin-right: 10px")
      span(style="font-weight: bold")= team.fundraiser.purpose
  table.table
    tbody
      tr
        th Aktualny postęp
        td #{team.total_fundraiser} zł

app/views/partials/_goals.html.slim
.ft-content.row-fluid role='main'
  .span8
    section.campaigns
      h1.lead Wybierz cel
      - for campaign in @campaigns
        - url = team_campaign_path(team)
        = simple_form_for [team, campaign], method: 'put', url: url do |f|
          h2
            = image_tag campaign['picture']
            = link_to campaign['purpose'], campaign['link']
            = hidden_field_tag 'campaign[slug]', campaign['slug']
            = f.submit 'Wybierz', :class => 'btn btn-info'
  - if team.fundraiser.present?
    .ft-sidebar.span4
      section.ft-goal= render 'partials/goal'

app/views/partials/_navigation.slim
- if can? :manage, team
  nav
    h1.hidden Nawigacja

    ul.nav.nav-tabs
      - if team.valid?
        li(class=(params[:action] == 'show' ? "active" : ""))
          = link_to 'Aktywność', team_path(team)
        li(class=(params[:page] == "goals" ? "active" : ""))
          = link_to 'Cel zbiórki', edit_team_path(team, :page => "goals")
        li(class=(params[:page] == "employees" ? "active" : ""))
          = link_to 'Pracownicy', edit_team_path(team, :page => "employees")
      li(class=(params[:action] == 'edit' && params[:page].blank? ? "active" : ""))
        = link_to 'Ustawienia firmy', edit_team_path(team)

app/views/partials/_post_form.slim
= simple_form_for [team, current_user, activity], html: { class: 'ft-post-form' } do |f|
  h1.lead Czym się dzisiaj pochwalisz?
  fieldset
    legend.hidden Nowy post
    .row-fluid
      .span9
        = f.input :description, :as => :text, :placeholder => "Na przykład: „Zrobiłem dzisiaj 30 pompek.”", :label => false
      .span3
        = f.submit 'Dodaj post', :class => "btn btn-primary btn-large"
    .row-fluid
      .help-block Napisz krótko o swojej ostatniej aktywności fizycznej i zmotywuj innych do tego samego!

app/views/partials/_progress_bar.slim
.ft-progress.progress.progress-success
  .hidden Aktualny status zbiórki
  .bar style="width: #{(team.total_fundraiser.to_f / team.budget * 100).round}%"
    = team.total_fundraiser
    span= "/#{team.budget} zł"

app/views/partials/_ranking.slim
h1.lead Ranking

table.table
  thead
    tr
      th #
      th Imię i nazwisko
      th Zebrana kwota
  tbody
    - team.best_users.each_with_index do |user, index|
      tr class=(user == current_user ? 'ft-rank-row--mine' : '')
        td= index + 1
        td= user.full_name
        td= "#{user.total_fundraiser} zł"

app/views/partials/_settings.html.slim
.ft-content.row-fluid role="main"
  .span8
    section
      h1.lead Ustawienia firmy
      = simple_form_for team, :class => "form-horizontal" do |f|
        = f.input :name
        = f.input :nip
        = f.input :budget
        = f.submit "Zapisz ustawienia"

app/views/partials/_top.html.slim
header.ft-header
  - if current_user.present?
    .pull-right
      .btn-group
        = link_to current_user.full_name, team_user_path(team, current_user), 
          :class => "btn btn-large"
        button.btn.btn-large.dropdown-toggle data-toggle="dropdown"
          .caret
        ul.dropdown-menu.pull-right role="menu"
          li
            = link_to "Wyloguj się", destroy_user_session_path, 
              :method => :delete
  .page-header
    h1
     ' Fittastic
     - if respond_to?(:team) && team.name.present?
      small= team.name